import { Metadata } from "next";
import Image from "next/image";
import { Title, ContactForm } from "@/components";
import { ContactSvg } from "@/constants/icons";

export const metadata: Metadata = {
  title: "Contact | React Portfolio",
  description: "Generated by Ahmet Topal",
};

const ContactPage = () => {
  return (
    <div className="dark:bg-zinc-700">
      <Title title="Contact With Me" />
      <div className="flex flex-col md:flex-row justify-center p-10 gap-20">
        <Image
          src={ContactSvg}
          width={400}
          height={400}
          alt="contact illustrations"
        />
        <ContactForm />
      </div>
    </div>
  );
};

export default ContactPage;
