import { Metadata } from "next";
import { Title, PortfolioCard } from "@/components";
import { PortfolioData } from "@/constants/data";

export const metadata: Metadata = {
  title: "Portfolio | React Portfolio",
  description: "Generated by Ahmet Topal",
};

const PortfolioPage = () => {
  return (
    <div className="dark:bg-zinc-700">
      <Title title="My Portfolio" />
      <div className="px-5">
        {PortfolioData.map((item, index: number) => {
          return (
            <div
              key={index}
              className="flex flex-col items-center justify-center"
            >
              <PortfolioCard
                image={item?.image}
                title={item?.title}
                description={item?.description}
                webLink={item?.webLink}
                androidLink={item?.androidLink}
                iosLink={item?.iosLink}
                tech={item?.tech}
                index={index}
              />
            </div>
          );
        })}
      </div>
    </div>
  );
};

export default PortfolioPage;
