import React from "react";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Portfolio | React Portfolio",
  description: "Generated by Ahmet Topal",
};

const PortfolioPage = () => {
  return (
    <div className="dark:bg-zinc-700">
      <div>portfolio</div>
    </div>
  );
};

export default PortfolioPage;
