import { Metadata } from "next";
import { Greeting, SkillsList, Title } from "@/components";
import { techStack } from "@/constants";

export const metadata: Metadata = {
  title: "Home | React Portfolio",
  description: "Generated by Ahmet Topal",
};

export default function Home() {
  return (
    <div className="flex flex-col">
      <Greeting />
      <div className="flex justify-center bg-white dark:bg-zinc-700">
        <div className="2xl:min-w-[50%] p-3 md:p-20">
          <Title title="Skills & Tools" />
          <SkillsList data={techStack} />
        </div>
      </div>
    </div>
  );
}
