import { Metadata } from "next";
import { Greeting } from "@/components";

export const metadata: Metadata = {
  title: "Home | React Portfolio",
  description: "Generated by Ahmet Topal",
};

export default function Home() {
  return (
    <div>
      <Greeting />
      <div>home</div>
    </div>
  );
}
